server:
  port: 8080
spring:
  cloud:
    gateway:
      mvc:
        routes:
          ## Movie Service
          - id: movie-service
            uri: lb://movie-service
            predicates:
              - Path=/movies/{segment}
            filters:
              - SetPath=/api/v1/movies/{segment}

          ## Catalog Service
          - id: catalog-service
            uri: lb://catalog-service
            predicates:
              - Path=/catalog/{segment}
            filters:
              - SetPath=/api/v1/catalog/{segment}


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: "health,info"