spring:
    data:
        mongodb:
            database: test
            port: 27027
    rabbitmq:
        username: guest
        password: guest
        host: localhost
        port: 5672
    cloud:
        openfeign:
            micrometer:
                enabled: true
server:
    port: 0
queue:
  serie:
    name: serieQueue

management:
  tracing:
    sampling:
      probability: 1.0
